#Docker compose para arrancar instalación de wordpress
version: '3.3'
services:
  db:
    container_name: 'local-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - '../mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: secreta
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_secreta

  wordpress:
      container_name: 'local-wordpress'
      depends_on:
        - db
      image: 'wordpress:latest'
      ports:
        - '80:80'
      environment:
        WORDPRESS_DB_HOST: 'db:3306'
        WORDPRESS_DB_USER: wordpress_user
        WORDPRESS_DB_PASSWORD: wordpress_secreta
        WORDPRESS_DB_NAME: wordpress_db
      volumes:
        - "../wordpress:/var/www/html"